### ISSUE TITLE
BNS Revolution

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#111]
Dear @gildor2 

i have issue export animation it's not appeared on the Export Folder here is a screenshot
![um](https://user-images.githubusercontent.com/29927382/49663678-10c1c300-fa58-11e8-8008-e6043a4e283d.png)

Engine Ver 4.20

**Comment by gildor2** [comment]
Dear @DemonRem 

If you'd strip your log even more,, and provide even less information, that'd be MUCH MORE helpful :D But actually it's not possible to provide less information than you did.

Also, please use forum. I'm about to close "issues" part of my github page because most of things here aren't "issues" but rather "misuse" or "I'm too busy to learn".

**Comment by DemonRem** [comment]
thank you @gildor2
