### ISSUE TITLE
Issue exporting models from Spyro Reignited Trilogy (PC version)

### ISSUE THREAD

**Issue by Magic-Nipples** [gildor2/UModel#136]
When attempting model swaps in the game (new mesh but it contains the same skeleton) the orientation of the bones seems to be broken. Some of them seem to be fine, but others are not, and I'm not sure of the pattern to exactly point to what parent bones cause this.

I believe this is part of the exporting process from umodel to the .psk format as importing that using the 3ds max script shows the incorrect bones. Same goes for Blender.

If you are able to correct this, or at the very least clarify what the issue might be, it would be really helpful with modding the game.

![umodel_K1OY9FMQX4](https://user-images.githubusercontent.com/15524356/64492426-4559e980-d239-11e9-9e71-37bee9ae57ab.png)

**Comment by gildor2** [comment]
There are 5 possibilities here.

1. You're just thinking that bones are wrong, but actually they're ok, Sorry, but lots of inexperienced users (talked an hour with one today) does not distinguish between bone helpers in Max and skeleton display in UE Viewer or Unreal Engine.

2, Some of the bones has special ANIMATION attributes which aren't supported at the moment. I'm just planning at the moment to support "use translation from mesh" per bone etc - it works for UE3, but not for UE4.

3. "Wrong bones" aren't used anywhere in geometry. So, bones are looking incorrectly, but skinned geometry is ok.

4. Game has something special in animation system.

5. Of course, there could be a bug in UE Viewer, but it is unlikely because otherwise the bug would appear before with other games.

**Comment by Magic-Nipples** [comment]
After further testing it seems to be pointing towards 3 with some controller bones that mess up the hierarchy. I don't believe the game uses any animation attributes really as manually replacing the animations along with the mesh skeleton seems to work fine. Anyways, thanks for the suggestions! Closing the issue.
