### ISSUE TITLE
vc32tools selects wrong Windows SDK

### ISSUE THREAD

**Issue by brendancboyle** [gildor2/UModel#25]
Hi Konstantin,

I found a bug in the recommended build tool vc32tools which prevents compilation on newer Windows SDK installs. I was able to replicate my findings using Windows 10 (Creators update insider preview) with VS 2015 and Windows Server 2012 R2 with VS 2013 (stock VC 2013 Azure image). When I run vc32tools it automatically tries to pick Windows SDK 7.0A, the lowest API level available on both systems. However, this is a bad choice because the 7.0A SDK only had the binaries folder, and is missing includes and libraries. This is a problem which causes the GL/gl.h not found error described in #24. Fortunately, this is easily resolved by copying over the libs and includes folders from SDK 7.1A to the 7.0A folder (C:\Program Files (x86)\Microsoft SDKs\Windows). I completely understand if this bug isn't worth your time, but I would consider updating the install instructions to mention this workaround.

Thanks,
Brendan

**Comment by gildor2** [comment]
Hi Brendan,

There are some misteries with GL folder, and with SDKs, so I did the same - copied missing include files from one SDK to another. There's no point of using most new SDK version because UModel won't use these features.

I even notices once, that I had broken SDK - missing header files - after installing another version of Visual Studio. For example, I used VS2013 to build UE4. However after installing VS2015 for building new version of UE4, older version stopped building with VS2013. I had such situation so many times, so I already gave up trying to fix everything.

Thanks,
Konstantin
