### ISSUE TITLE
Injustice 2 and umodel

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#42]
Gildor 

man I see you not going to add Injustice 2 PC Version is this correct , 
if I can help you in anyway to add this game tell me , will be great if umodel have support Injustice 2

**Comment by gildor2** [comment]
Yes, Injustice 2 PC uses UE3 instead of mobile version UE4. I'm not working on this game's support, I'd prefer to waste my time in a different way :)

What kind of help you're offering? There's someone else who's working on Injustice 2 support **in his own tool**, see here: http://www.gildor.org/smf/index.php/topic,3416.15.html
