### ISSUE TITLE
Deserialization of EnumProperty

### ISSUE THREAD

**Issue by AeonLucid** [gildor2/UModel#48]
Hi,

I was reading through UnObject and found this.
https://github.com/gildor2/UModel/blob/a5a806c0ab1da250992be04ee000b290552ccfc9/Unreal/UnObject.cpp#L1331

It actually serializes to something, it's a `FName` (Int32 Index, Int32 Number)  containing the name of the enum value.

**Comment by gildor2** [comment]
Hi,

For the files mentioned in forum thread (those one in code comment), EnumProperty wasn't serialized at all. But "StopPos" was wrong, and I'm fixing it. UE4 exists in public for 4 years, and that was the first appearance of EnumProperty in files, so I don't have anything else to verify. Do you have any files which crashed with this new code?

**Comment by AeonLucid** [comment]
Sorry, was not sure if you knew already and the thread was not very clear in that either.
I don't have a sample as I was just looking through the code.

**Comment by gildor2** [comment]
So, that was just a question about the code then?

**Comment by AeonLucid** [comment]
No it was more like sharing what I know. But if you already knew it does not really help you at all.

**Comment by gildor2** [comment]
Ok, thank you for heads up. I think you meant UEnumProperty::SerializeItem method. According to code, this method must be called, and it will serialize FName as data. However, files from the game mentioned above has no data for UEnumProperty - and at the same time, FPropertyTag.Size field is set like this FName was serialized. I suppose this is a bug in engine (not in that particular game), because problems in property data blocks appears from time to time in different games, starting with very first Unreal engine. UModel has many workarounds for these bugs.
