### ISSUE TITLE
New game called "paladins" - unknown compression flags: 514

### ISSUE THREAD

**Issue by babbelnedd** [gildor2/UModel#6]
Hey I'm trying to extract files from a new UE3 game called [Paladins](http://www.paladins.com/). Unfortunately I'm getting the error

    *** ERROR: appDecompress: unknown compression flags: 514

Is there a chance you'll investigating into this?

```
umodel.exe  x\GFxUI.upk
Detected game root x (no recurse)
Found 130 game files (2 skipped)
Loading package: GFxUI.upk Ver: 893/0 Engine: 10897 Names: 898 Exports: 777 Imports: 58 Game: 8000
******** x\GFxUI.upk ********
*** ERROR: appDecompress: unknown compression flags: 514
appDecompress:CompSize=35185 UncompSize=131072 Flags=0x202 <- DecompressBlock:block=B1+8971 <- FUE3ArchiveReader::PrepareBuffer <- FUE3ArchiveReader::Serialize <- FArchive::ByteOrderSerialize <- FString<< <- Name:0 <- UnPackage::LoadNameTable <- UnPackage::UnPackage:GFxUI.upk, ver=893/0, game=8000 <- UnPackage::LoadPackage:x\GFxUI.upk <- Main:umodel_version=413
```
Using the latest realase 

```
umodel.exe -version
UE Viewer (UModel)
Compiled Nov 13 2015 (git 413)
Copyright 2007-2015 Konstantin Nosov (Gildor). All rights reserved.
http://www.gildor.org/en/projects/umodel
```

**Comment by gildor2** [comment]
Usually people submitting bugs on the forum.

"unknown compression flags" are usually means either encryption, or custom compressor. I'm rarely dealing with such issues because most likely I'll not be able to support it, plus developers can notice that their encryption was broken and submit a new one in new patch, breaking UModel's compatibility again,

Another reason for not doing that: when developers apply encryption, they silently say: "keep off from our data" (another possible reason is to use some better compression, but it is very unlikely). I'd prefer to keep UModel to be legal tool and to not provide any troubles to them.

**Comment by babbelnedd** [comment]
Well, that makes sense. Thanks for your answer.
